apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-website-ingress
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devops-website-service
            port: {number: 80}
